# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 03:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('FirstName', models.CharField(blank=True, default=b'', max_length=100)),
                ('LastName', models.CharField(blank=True, default=b'', max_length=100)),
                ('companyName', models.CharField(blank=True, default=b'', max_length=100)),
                ('Age', models.IntegerField()),
                ('City', models.CharField(blank=True, default=b'', max_length=100)),
                ('State', models.CharField(blank=True, default=b'', max_length=100)),
                ('Zip', models.IntegerField()),
                ('Email', models.EmailField(blank=True, max_length=70)),
                ('Web', models.URLField()),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
